### ISSUE TITLE
Add environment variable for configuring MongoDB connection options

### ISSUE THREAD

**Issue by magnusbaeck** [eiffel-community/eiffel-graphql-api#25]
### Description
The MongoDB connection parameters are currently picked up from environment variables in [database.py](https://github.com/eiffel-community/eiffel-graphql-api/blob/master/src/eiffel_graphql_api/graphql/db/database.py). Each parameter has a separate variable. This makes adding support for additional parameters tedious and inflexible. We should support an environment variable that contains the query string part of the connection URL, i.e. something like this:

    MONGODB_CONNOPTIONS=replicaSet=foo&authSource=random-db-name

I still think it makes sense to have separate variables for the most important parameters (hostname, username, ...).

### Motivation
Looking through the [connection string options documentation](https://docs.mongodb.com/manual/reference/connection-string/#connections-connection-options) there are quite a few options that could be useful and adding separate variables for all of them isn't reasonable.

### Exemplification
If the MongoDB server's authentication database differs from the default ("admin") you need to specify this in the URL or you won't be able to authenticate. There currently is no option to specify the authentication database.

### Benefits
Less database.py churn and fewer environment variables to document.

### Possible Drawbacks
A percent-encoded string that goes straight into a URL isn't a great configuration interface, but it's a reasonable price to pay for flexibility.

**Comment by magnusbaeck** [comment]
Actually, we should probably drop all the environment variables and just have a single MONGODB_URL variable. Apart from what's described in the issue description we also don't support multiple hosts, neither with the host list comma-separated nor with the mongodb+srv URL scheme.

Such a change would of course be backwards incompatible, but I don't think we have that many users that it's a real problem. We're not even making real releases.

**Comment by fredjn** [comment]
The backwards compatibility breakage is definitely a non-issue at this stage I would say.

**Comment by t-persson** [comment]
I agree with @fredjn - it's a non-issue. Please make the change and we'll increase major version for clarity.
