### ISSUE TITLE
Improve insertion performance by not creating indexes all the time

### ISSUE THREAD

**Issue by magnusbaeck** [eiffel-community/eiffel-graphql-api#54]
### Description
When inserting documents with 
[eiffel_graphql_api.graphql.db.database.insert_to_db](https://github.com/eiffel-community/eiffel-graphql-api/blob/master/src/eiffel_graphql_api/graphql/db/database.py) we always create indexes for `meta.id` and `links.target`. This is almost always unnecessary and triples the number of server round-trips.

I had two queues with thousands of messages and two storage.py processes running to consume from those queues and insert into the same database. Both processes were able to consume at a rate of about 175 messages/s:

![image](https://user-images.githubusercontent.com/9032797/95192795-00550d80-07d3-11eb-9751-4299933680cd.png)

I don't think RabbitMQ or MongoDB is the limiting factor. I know that the RabbitMQ cluster in question can deliver messages at a higher rate, and since we got the same insertion performance regardless of if we had one or two queue con MongoDB clients I'm guessing we weren't limited by MongoDB either.

I don't know what the best course of action is here. Perhaps graphql-api shouldn't be responsible for creating indexes at all? Indexes aren't one-size-fits-all so if it should keep creating indexes the list of indexed fields should be configurable. We'd also have to track which indexes have been created, or keep doing it like today but limit the rate to once every _N_ minutes.

### Motivation
Most deployments won't reach 175 messages/second sustained load so this isn't a critical problem, but burst rates exceeding that aren't unlikely and delays in the availability of events in en ER can be problematic. Also, additional requests place higher load on MongoDB even if they're no-ops.

### Benefits
Faster availability of events in the event repository under situations of high load. Also decreased database load.

### Possible Drawbacks
None except increased code complexity.

**Comment by t-persson** [comment]
Awesome test. Thank you for doing this.

I'm pretty sure that the indexing within storage.py was done because the collections are created dynamically if a new event type comes along.
Would it be possible to create all collections that don't exist and index them on startup of storage.py instead? If so, it would just be a slow startup time on the program instead of all requests being slowed down.

**Comment by magnusbaeck** [comment]
> Would it be possible to create all collections that don't exist and index them on startup of storage.py instead?

Depends on the cost of a collection. A deployment might not need all event types and then there would be perpetually empty collections.

**Comment by t-persson** [comment]
We could also check for the index once and store that the index exists in a global data store.
This would mean that we'd check for an index at least once per collection per storage instance. Not so bad right? :)

**Comment by magnusbaeck** [comment]
Sure, that's a possible optimization but my question of whether this is something storage.py should be doing at all remains open.

How about making the indexed fields configurable via an environment variable? By defaulting to the current fields we get reasonable (and backwards compatible) default behavior, people who want to have additional fields indexed can make that happen, and those who want indexes managed entirely outside storage.py can just set the variable to an empty list.

**Comment by t-persson** [comment]
Agreed. Sounds like a better solution
