### ISSUE TITLE
Provide ER compatibility API

### ISSUE THREAD

**Issue by magnusbaeck** [eiffel-community/eiffel-graphql-api#7]
### Description
We should have a compatibility API that allows REMReM and other tools that can look things up in the Ericsson ER to work with this service.

This functionality could be included in the existing Flask app ([src/eiffel_graphql_api/graphql/api.py](https://github.com/eiffel-community/eiffel-graphql-api/blob/master/src/eiffel_graphql_api/graphql/api.py)) or it could be a separate app. I have no strong opinion either way except that a separate app would be slightly more flexible.

### Motivation
The link lookup functionality in REMReM Generate is quite useful and makes it easy for clients to add links to their messages without having their own repository dependency.

### Benefits
Increases the value of REMReM Generate & Publish.

### Possible Drawbacks
None apart from the usual caveats of having more code with more features.

**Comment by t-persson** [comment]
Would it be possible to make this as an extension to REMReM instead?
I feel that it would be up to that service to know how to communicate with APIs.

If that's not possible, I am a strong advocate of creating this compatibility API wherever it's easiest. Just don't the GraphQL completely dependent on this extension.

**Comment by t-persson** [comment]
Wrote an issue on eiffel-remrem-generate with the hope that it can be fixed there :)

**Comment by magnusbaeck** [comment]
Is there any reason to layer the ER API on top of eiffel-graphql-api? Wouldn't it make more sense to simply implement the (soon to be) standardized ER API directly on top of MongoDB as a separate component? Sure, it's convenient to have a single MongoDB configuration and code hosted in a single proess if you're using eiffel-graphql-api and want an ER API, but for sites _not_ interested in the GraphQL API it'd be weird to couple them.

I suggest we close this issue and create a new repository that'll contain a lightweight ER API for MongoDB backends.

**Comment by t-persson** [comment]
The reasoning is that since we're providing an ER API, this API should be compatible with all tools that require an ER.
Instead of having users that want to use both Eiffel Intelligence and ETOS (for example) be required to install two event repository APIs.

If we think that a lightweight ER API for MongoDB is a better alternative, then I'm all for it, just providing the reasoning :)

**Comment by magnusbaeck** [comment]
Yes, sites wanting both the GraphQL and the ER APIs would have to deploy two things instead of just one. That's what speaks for bundling. On the other hand those only interested in one the APIs will get both.

Technically an ER API implementation in this git would probably be independent from the GraphQL queries (rather than be a layer on top of it) since the response from the GraphQL queries isn't the original Eiffel events (because some attributes have been renamed to fit the GraphQL schema). This technical independence is, I think, what speaks for not bundling these APIs in the same git.

**Comment by magnusbaeck** [comment]
I've been thinking about this some more and as I just commented in #54 I think the GraphQL API should be treated as a thin API layer, perhaps one of many, rather than as something that "owns" the database and creates indexes and provides other means of accessing it. I'm going to go ahead and close this issue and will initiate the process of creating a new repository for the lightweight ER API.
